# Docker Compose for PM-App Development
version: '3.8'

services:
  # Main application (development mode)
  pm-app-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: pm-app-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.docker
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - pm-app-dev-network
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  pm-app-dev-network:
    driver: bridge
