# Docker Compose for Database Only (Local Development)
version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:16-alpine
    container_name: pm-app-postgres-local
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pmapp
      POSTGRES_USER: pmapp_user
      POSTGRES_PASSWORD: secure_local_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pmapp_user -d pmapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Development (Optional)
  redis:
    image: redis:7-alpine
    container_name: pm-app-redis-local
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass secure_redis_password
    volumes:
      - redis_local_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_local_data:
    driver: local
  redis_local_data:
    driver: local
